config/routes.rb
Rails.application.routes.draw do
	root "sessions#new"
	resources :favorites
	resources :posts do
    resource :favorites
		collection do
			post :confirm
		end
	end
	resources :sessions
	resources :users do
		resources :favorites
	end
	mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates_uniqueness_of :post_id, scope: :user_id
end

app/models/post.rb
class Post < ApplicationRecord
  validates :content, presence: true
  validates :image, presence: true
  mount_uploader :image, ImageUploader
  belongs_to :user
  has_many :favorites, dependent: :destroy
	has_many :favorite_users, through: :favorites, source: :user
end

app/models/user.rb
class User < ApplicationRecord
  validates :name,  presence: true, length: { maximum: 30 }
	validates :email, presence: true, length: { maximum: 255 },
										format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
	before_validation { email.downcase! }
	has_secure_password
	validates :password, presence: true, length: { minimum: 6 }

	has_many :posts, dependent: :destroy
	has_many :favorites, dependent: :destroy

	mount_uploader :image, ImageUploader

	def already_favorited?(post)
    self.favorites.exists?(post_id: post.id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper

  def authenticate_user
    if current_user == nil
      flash[:notice] = "ログインが必要です。"
      redirect_to new_session_path
    end
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def index
    @posts = Post.joins(:favorites).where(favorites:{user_id: params[:user_id]})
  end

  def create
    @favorite = current_user.favorites.create(post_id: params[:post_id])
    redirect_back(fallback_location: root_path)
  end

  def destroy
    @post = Post.find(params[:post_id])
    @favorite = current_user.favorites.find_by(post_id: @post.id)
    @favorite.destroy
    redirect_back(fallback_location: root_path)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user,{only: [:new, :create, :confirm, :edit, :update, :show, :destroy]}

  def index
    @posts = Post.all
  end

  def new
    if params[:back]
      @post = Post.new(post_params)
    else
      @post = Post.new
    end
  end

  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      PostMailer.post_mail(@post).deliver
      redirect_to posts_path
    else
      render :new
    end
  end

  def confirm
    @post = current_user.posts.build(post_params)
    render :new if @post.invalid?
  end

  def edit
    @post = Post.find(params[:id])
    if @post.user != current_user
      redirect_to posts_path
    end
  end

  def show
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to posts_path
    else
      render :edit
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_path
  end

  private
  def post_params
    params.require(:post).permit(:content, :image, :image_cache)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :authenticate_user, only: :destroy
  def new
    if logged_in?
      redirect_to posts_path
    end
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to posts_path
    else
      flash.now[:danger] = 'ログインに失敗しました'
      render :new
    end
  end

  def destroy
    session.delete(:user_id)
    flash.now[:notice] = 'ログアウトしました'
    redirect_to new_session_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user, {only: [:edit, :update]}

  def new
    @user = User.new
    if logged_in?
      redirect_to posts_path
    end
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to user_path(@user.id)
      session[:user_id] = @user.id
    else
      render :new
    end
  end

  def edit
    @user = User.find(params[:id])
    if @user != current_user
      redirect_to user_path(current_user), alert: "不正なアクセスです。"
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def update
    @user = User.find_by(id: params[:id])
    if @user.update(user_params)
      redirect_to user_path
    else
      render :edit
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password,
                                :password_confirmation, :image, :image_cache)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
  def choose_new_or_edit
    if action_name == 'new'
      confirm_posts_path
    elsif action_name == 'edit'
      post_path
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  
  def logged_in?
    current_user.present?
  end
end

app/views/application/_nav.html.erb
<% if logged_in? %>
  <nav class="navbar navbar-default">
    <div class="container-fluid container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <div class="navbar-brand">
          <%= link_to 'instantgram', posts_path %>
        </div>
      </div>
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to '投稿する', new_post_path %></li>
          <li><%= link_to 'ホームに戻る', posts_path %></li>
          <li><%= link_to "プロフィール", user_path(current_user.id) %></li>
          <li><%= link_to "ログアウト", session_path(current_user.id), method: :delete %></li>
        </ul>
      </div>
    </div>
  </nav>
<% end %>

app/views/favorites/index.html.erb
<h2>いいねした写真</h2>
<% for post in @posts %>
  <div class="container">
    <div class="row text">
      <div class= "col-sm-8 col-sm-offset-2">
          <div class="post-prof">
            <% if post.user.image && post.user.image.url %>
              <%= image_tag post.user.image.url(:thumb100), class: "img-circle" %>
            <% else %>
              <img src="/avatar.png">
            <% end %>
            <%= link_to post.user.name, [post.user] %>
          </div>
          <div class="post-img">
            <% if post.image && post.image.url %>
              <%= image_tag post.image.url ,class: "img-responsive" %>
            <% end %>
          </div>

          <div class = "post-icon">
            <% if post.user.id != current_user.id %>
              <% if current_user.already_favorited?(post) %>
                <%= link_to post_favorites_path(post), method: :delete do %>
                  <span class="glyphicon glyphicon-heart" aria-hidden="true" style="font-size: 36px"></span>
                <% end %>
                <%= post.favorites.count %>
              <% else %>
                <%= link_to post_favorites_path(post), method: :post do %>
                  <span class="glyphicon glyphicon-heart-empty" aria-hidden="true" style="font-size: 36px"></span>
                <% end %>
                <%= post.favorites.count %>
              <% end %>
            <% end %>
          <div>

            <div class="post-text">
              <p><%= post.content %></p>
              <%= post.created_at.strftime("投稿日：%Y年%m月%d日") %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Instantgram</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'nav' %>
    <% if flash[:notice]%>
      <div class="row">
        <div class="col-md-6 col-md-offset-3">
          <%= flash[:notice] %>
        </div>
      </div>
    <% elsif flash[:danger] %>
      <div class="row">
        <div class="col-md-6 col-md-offset-3">
          <%= flash[:danger] %>
        </div>
      </div>
    <% end %>
    <div class='container'>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: @post, local: true, url:choose_new_or_edit) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= @post.errors.count %>件のエラーがあります。</h2>
      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
    <%= f.text_field :content, class: 'form-control input-lg',:placeholder => "メッセージをシェアしよう"%>
    <%= f.hidden_field :content　%>
    <%= image_tag @post.image.url(:thumb) if @post.image && @post.image.url %>
    <%= f.file_field(:image,{:class => 'btn-primary'})  %>
    <%= f.hidden_field :image_cache　%>
    <div class="text-right">
      <%= link_to '戻る', posts_path, class:"btn btn-warning" %>
      <%= f.submit("投稿する", class:"btn btn-primary") %>
    <div>
<% end %>

app/views/posts/confirm.html.erb
<h1>投稿内容</h1>
<%= form_with(model: @post, url: posts_path, local: true) do |f| %>
  <div class="panel-body row">
    <p class="post-content"><%= @post.content %></p>
    <%= f.hidden_field :content %>
    <%= image_tag @post.image.url(:thumb) %>
    <%= f.hidden_field :image_cache %>
  </div>
  <%= f.submit("投稿する", class:"btn btn-primary") %>
<% end %>
<%= form_with(model:@post, url:new_post_path, local:true, method:"get") do |f| %>
  <%= f.hidden_field :content %>
  <%= f.hidden_field :image_cache %>
  <%= f.submit("戻る", name: "back", class:"btn btn-warning") %>
<% end %>

app/views/posts/create.html.erb
<h1>Posts#create</h1>
<p>Find me in app/views/posts/create.html.erb</p>

app/views/posts/edit.html.erb
<%= render 'form' %>

app/views/posts/index.html.erb
<p><%= notice %></p>
<% for post in @posts %>
  <div class="container">
    <div class="row text">
      <div class= "col-sm-8 col-sm-offset-2">
          <div class="post-prof">
            <% if post.user.image && post.user.image.url %>
              <%= image_tag post.user.image.url(:thumb100), class: "img-circle" %>
            <% else %>
              <img src="/avatar.png">
            <% end %>
            <%= link_to post.user.name, post_path(post.id) %>
          </div>
          <div class="post-img">
            <% if post.image && post.image.url %>
              <%= image_tag post.image.url ,class: "img-responsive" %>
            <% end %>
          </div>

          <div class = "post-icon">
            <% if post.user.id != current_user.id %>
              <% if current_user.already_favorited?(post) %>
                <%= link_to post_favorites_path(post), method: :delete do %>
                  <span class="glyphicon glyphicon-heart" aria-hidden="true" style="font-size: 36px"></span>
                <% end %>
                <%= post.favorites.count %>
              <% else %>
                <%= link_to post_favorites_path(post), method: :post do %>
                  <span class="glyphicon glyphicon-heart-empty" aria-hidden="true" style="font-size: 36px"></span>
                <% end %>
                <%= post.favorites.count %>
              <% end %>
            <% end %>

            <% if post.user.id == current_user.id %>
              <div class="post-links">
                <%= link_to edit_post_path(post.id) ,data: {confirm: "本当に編集していいですか？"} do %>
                    <span class="glyphicon glyphicon-pencil g-links" aria-hidden="true"></span>
                <% end %>
                <%= link_to post_path(post.id), method: :delete ,data: { confirm: '本当に削除してよろしいですか？' } do %>
                    <span class="glyphicon glyphicon-trash g-links" aria-hidden="true"></span>
                <% end %>
              </div>
            <% end %>
          <div>

            <div class="post-text">
              <p><%= post.content %></p>
              <%= post.created_at.strftime("投稿日：%Y年%m月%d日") %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/posts/new.html.erb
<%= render 'form' %>

app/views/posts/show.html.erb
<p>内容: <%= @post.content %></p>
 <%= image_tag @post.image.url %>

 <%= link_to '戻る', posts_path, class:"btn btn-warning" %>

app/views/users/edit.html.erb
<%= form_with(model: @user, local: true) do |form| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= @user.errors.count %>件のエラーがあります。</h2>
      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div  class="col-xs-5">
      <% if @user.image && @user.image.url %>
        <%= image_tag @user.image.url(:thumb100), class: "img-circle" %>
      <% else %>
        <img src="/avatar.png">
      <% end %>
    <br><br>
    <%= form.file_field :image %>
    <br>
    <div class="form-group">
      <%= form.label "ユーザー名:" %>
      <%= form.text_field :name, class:"form-control" %>
    </div>
    <div class="form-group">
      <%= form.label "メールアドレス:" %>
      <%= form.email_field :email, class:"form-control" %>
    </div>
    <div class="form-group">
      <%= form.label :password %>
      <%= form.password_field :password, class:"form-control" %>
    </div>
    <div class="form-group">
      <%= form.label :password_confirmation %>
      <%= form.password_field :password_confirmation, class:"form-control" %>
    </div>
    <%= form.submit("更新する", class:"btn btn-info btn-block") %>
    <%= link_to "戻る", :back, class:"btn btn-default btn-block" %>
  </div>
<% end %>

app/views/users/new.html.erb
<div class="form">
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this <%= @user.name %> from being saved:</h2>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="side">
  </div>
    <%= form_with(model: @user, local: true) do |f| %>
      <h1 class="logo-name">Instantgram</h1>
      <p>登録して友達の写真や動画をチェックしよう</p>
      <%= f.text_field :name ,class: "form-group form-control form-control-lg",:placeholder => "フルネーム" %>
      <%= f.email_field :email ,class: "form-group form-control form-control-lg",:placeholder => "メールアドレス" %>
      <%= f.password_field :password ,class: "form-group form-control form-control-lg", :placeholder => "パスワード" %>
      <%= f.password_field :password_confirmation, class: "form-group form-control form-control-lg", :placeholder => "パスワード（確認用）" %>
      <%= f.submit "登録する", class:"btn btn-primary btn-md btn-block" %>
    <% end %><hr><br>
    <p>アカウントをお持ちですか？</p>
    <%= link_to "ログインする", new_session_path, class:"btn btn-success btn-md btn-block"  %>
</div>

app/views/users/show.html.erb
<% if @user.image && @user.image.url %>
    <%= image_tag @user.image.url(:thumb100), class: "img-circle"  %>
<% else %>
    <%= image_tag '/avatar.png', class: "img-circle"  %>
<% end %>

<p>
  <strong>ユーザー名:</strong>
  <%= @user.name %>
</p>

<% if @user.id == current_user.id %>
  <p>
    <strong>メールアドレス:</strong>
    <%= @user.email %>
  </p>
<% end %>
<div class="text-left">
    <%= link_to 'いいねした写真', [@user, :favorites], class:"btn btn-success"  %>
    <% if @user.id == current_user.id %>
      <%= link_to 'プロフィールを編集', edit_user_path(@user), class:"btn btn-info" %>
    <% end %>
</div>
<div class="text-right">
  <%= link_to '一覧画面に戻る', posts_path, class:"btn btn-default" %>
</div>